name: Deploy web stage // stage environment worker
on:
  push:
    branches:
      - stage
concurrency:
  group: deploy-stage
  cancel-in-progress: true
jobs:
  deploy:
    environment: stage
    runs-on: ubuntu-latest
    env:
      WRANGLER_SEND_METRICS: false
      TURBO_TELEMETRY_DISABLED: 1
      NEXT_TELEMETRY_DISABLED: 1
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: setup pnpm
        uses: pnpm/action-setup@v4
      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml
      - name: get node version
        id: node
        run: |
          echo "version=$(node -v)" >> $GITHUB_OUTPUT
      - name: get node_modules cache
        uses: actions/cache@v4
        id: node_modules
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('*/pnpm-lock.yaml') }}-${{ steps.node.outputs.version }}
      - name: cache turbo build
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: ${{ runner.os }}-turbo-
      - name: install dependencies
        run: pnpm install --frozen-lockfile
      - name: build @repo/** scoped packages inside packages/**
        run: pnpm turbo build --filter=@repo/*{./packages/**}
      - name: deploy to cloudflare Worker // stage
        working-directory: apps/web
        env:
          NEXT_PUBLIC_POSTHOG_KEY: ${{ secrets.NEXT_PUBLIC_POSTHOG_KEY }}
          NEXT_PUBLIC_POSTHOG_HOST: ${{ secrets.NEXT_PUBLIC_POSTHOG_HOST }}
          NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.NEXT_PUBLIC_SENTRY_DSN }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          NEXT_PUBLIC_SENTRY_CSP_REPORT_ENDPOINT: ${{ secrets.NEXT_PUBLIC_SENTRY_CSP_REPORT_ENDPOINT }}
          SENTRY_ORG: ${{secrets.SENTRY_ORG}}
          SENTRY_PROJECT: ${{secrets.SENTRY_PROJECT}}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          POLAR_ACCESS_TOKEN: ${{ secrets.POLAR_ACCESS_TOKEN }}
          POLAR_WEBHOOK_SECRET: ${{ secrets.POLAR_WEBHOOK_SECRET }}
        timeout-minutes: 11
        run: pnpm deploy:stage
