name: Production

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main

concurrency:
  group: production-${{ github.workflow }}
  cancel-in-progress: false

env:
  NEXT_TELEMETRY_DISABLED: 1
  TURBO_TELEMETRY_DISABLED: 1

jobs:
  deploy-web-production:
    name: Deploy Website (Production)
    runs-on: blacksmith-4vcpu-ubuntu-2204
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - uses: ./.github/actions/setup
      - uses: ./.github/actions/infisical
        with:
          env-slug: prod
          secret-path: "github-actions"

      - name: Pull Vercel environment
        run: pnpx vercel env pull .env --yes --environment=production --token=$VERCEL_TOKEN

      - name: Pull Vercel project config
        run: pnpx vercel pull --yes --environment=production --token=$VERCEL_TOKEN

      - name: Build
        run: pnpx vercel build --prod --token=$VERCEL_TOKEN

      - name: Deploy
        run: pnpx vercel deploy --prebuilt --prod --archive=tgz --token=$VERCEL_TOKEN
